const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE:'CHANGE_LANGUAGE',
    
    //login
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    
    //user
    GET_ALL_USERS_SUCCESS: 'GET_ALL_USERS_SUCCESS',
    GET_ALL_USERS_FAILED: 'GET_ALL_USERS_FAILED',
    GET_ALL_USER_BY_ID_SUCCESS: 'GET_ALL_USER_BY_ID_SUCCESS',
    GET_ALL_USER_BY_ID_FAILED: 'GET_ALL_USER_BY_ID_FAILED',
    
    //Category
    GET_ALL_CATEGORY_SUCCESS: 'GET_ALL_CATEGORY_SUCCESS',
    GET_ALL_CATEGORY_FAILED: 'GET_ALL_CATEGORY_FAILED',

    //Vocabulary
    GET_ALL_VOC_SUCCESS: 'GET_ALL_VOC_SUCCESS',
    GET_ALL_VOC_FAILED: 'GET_ALL_VOC_FAILED',
    GET_ALL_LEARNED_VOC_SUCCESS: 'GET_ALL_LEARNED_VOC_SUCCESS',
    GET_ALL_LEARNED_VOC_FAILED: 'GET_ALL_LEARNED_VOC_FAILED',
    
})

export default actionTypes;