# Generated by Django 5.1.7 on 2025-03-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0002_user_is_active_user_is_staff_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
