# Generated by Django 5.1.7 on 2025-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be', '0004_alter_vocabulary_word'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='image',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='audio_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='image_path',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
